config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def edit
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: 'Flat was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_url, notice: 'Flat was successfully destroyed.'
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for flat do |f| %>
  <div class="form-inputs">
    <%= f.input :name, label: 'Name:' %>
    <%= f.input :address, label: 'Address:' %>
    <%= f.input :description, label: 'Description:' %>
    <%= f.input :price_per_night, label: 'Price per night:' %>
    <%= f.input :number_of_guests, label: 'Number of guests:' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flats</h1>

<div class="row row-cols-3">
  <% @flats.each do |flat| %>
    <div class="col">
      <div class="card">
        <%= image_tag "moon.jpeg", alt: "card picture", height: 200, width: "auto" %>
        <div class="card-body">
          <h5 class="card-title mb-3"><%= flat.name %></h5>
          <h6 class="card-subtitle mb-3"><%= flat.address %></h6>
          <i class="card-text fa-solid fa-people-line me-2"><%= flat.number_of_guests %></i>
          <i class="card-text fa-solid fa-euro-sign me-2"><%= flat.price_per_night %></i>
          <%= link_to "More info", flat_path(flat) %>
          <%= link_to "Edit", edit_flat_path(flat) %>
          <%= link_to "Remove", flat, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/show.html.erb
<div class="row row-cols-3">
  <div class="col">
    <div class="card">
      <img src="../../assets/images/moon.jpeg" class="card-img-top" alt="card picture">
      <div class="card-body">
        <h5 class="card-title"><%= @flat.name %></h5>
        <h6 class="card-subtitle"><%= @flat.address %></h6>
        <i class="card-text fa-solid fa-people-line"><%= @flat.number_of_guests %></i>
        <i class="card-text fa-solid fa-euro-sign"><%= @flat.price_per_night %></i>
        <%= link_to "More info", flat_path %>
        <%= link_to "Edit", edit_flat_path %>
        <%= link_to "Remove", @restaurant, method: :delete %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar border-bottom mb-5">
      <div class="ms-5 mt-2">
        <i class="fa-brands fa-airbnb"></i>
        <%= link_to "Simple Airbnb", flats_path, class: "icon" %>
      </div>
      <%= link_to "Add Flat", new_flat_path, class: "btn btn-primary me-5" %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>